-- AlterTable
ALTER TABLE "Wallet" ADD COLUMN     "cash" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "dateLastUpdated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "datePublicUpdated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "lastUpdatedValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "publicWalletValue" DOUBLE PRECISION NOT NULL DEFAULT 0;
